let sectionObjetivos =  new Container('Objetivos')
sectionObjetivos.addItem('Aplicar meus conhecimentos adquiridos durante a matéria de modo prático e didátido')
sectionObjetivos.addItem('Praticar e aprimorar minhas soft skills. Tais como trabalho em equipe, criatividade e comunicação')
sectionObjetivos.addItem('Contribuir com a comunidade acadêmica da UFC')

let sectionTecnologias = new Container('Tecnologias')
sectionTecnologias.addItem('Java (intermediário)', 'POO, introdução à JDBC e introdução à JavaFX')
sectionTecnologias.addItem('MySQL (básico/intermediário)', 'Criação de tabelas, consulta de dados e relacionamentos entre tabelas')
sectionTecnologias.addItem('HTML(intermediário)', 'estruturação e uso semântico de tags')
sectionTecnologias.addItem('CSS (intermediário)', 'Estilizações básicas e uso de variáveis')
sectionTecnologias.addItem('JavaScript (básico/intermediário)', 'Fundamentos e introdução à programação orientada a objetos em js')
sectionTecnologias.addItem('Bootstrap (básico)', 'Introdução ao uso do bootstrap e criação de sites responsivos')
sectionTecnologias.addItem('Git e Github (básico)', 'Introdução aos comandos básicos do git e versionamento de código')
sectionTecnologias.addItem('Linguagem C (básico)', 'Introdução a sintaxe básica')

let sectionHabilidades = new Container('Habilidades')
sectionHabilidades.addItem('Prototipação com figma', 'Autodidata')
sectionHabilidades.addItem('Metodologia ágil', 'Estudada ao longo da cadeira de "processos de software" - UFC')
sectionHabilidades.addItem('Pacote Office', 'Cursos de Word, Excel e Power Point realizados na fundação Bradesco')
sectionHabilidades.addItem('Introdução à psicologia das cores', 'Leitura da “Psicologia das cores: Como as cores afetam a emocao e a razao')
sectionHabilidades.addItem('UI/UX', 'Autodidata')

document.getElementById('objetivos').appendChild(sectionObjetivos.getContainer())
document.getElementById('tecnologias').appendChild(sectionTecnologias.getContainer())
document.getElementById('habilidades').appendChild(sectionHabilidades.getContainer())